
[package]
name = "inyew"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["MeiHui FAN <mhfan@ustc.edu>"]
description = "Page for 24-Game/Puzzle/Challenge"
#repository = "https://github.com/mhfan/inyew

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
serde = "1.0"
reqwasm = "0.5"
yew-router = "0.16"
gloo = "0.8"
rand = "0.8"

[dependencies.getrandom]
features = [ "js", ]
version  = "0.2"

[dependencies.web-sys]
features = [ "HtmlInputElement", ]
version  = "0.3"

[profile.dev]
incremental = true

[workspace]

