
[build]
target = "index.html"
release = false
dist = "dist"

public_url = "/inyew/"
# "/{project_name}/" for {username}.github.io/{project_name}, "/" for {username}.github.io

[watch]
watch = [ "index.html", "src/", "assets/css/", ]

[clean]
dist = "dist"
#cargo = false

[[hooks]]
command = "sh"
stage = "pre_build"
# run tailwind build with webpack
#command_arguments = [ "-c", "npm run build_css_webpack", ]
command_arguments = [ "-c", "npm run build_css", ]

#[serve]
#address = "0.0.0.0"
#port = 8080
#open = false

