
name: Publish gh pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:  # configure the environment
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: rust-toolchain
      #uses: dtolnay/rust-toolchain@stable
      #with:
      #  targets: wasm32-unknown-unknown
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown

    - name: trunk-action
      uses: jetli/trunk-action@v0.4.0

    # build css and rust
    - name: run trunk
      run: trunk build --release

    # deploy for github.io
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: dist
        # cname: abex.dev
